import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    // flex: 1,
    // paddingBottom: 60,
    backgroundColor: '#FFFFFF',
  },
  HeaderContainer: {
    width: '100%',
    height: 200,
    backgroundColor: '#7165E3',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  ActivityCardContent: {
    backgroundColor: '#7C6EFF',
    borderRadius: 15,
    width: 62,
    height: 62,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoContainer: {
    flexDirection: 'row',
    paddingHorizontal: 15,
  },
  personalInfo: {
    fontSize: 16,
    color: '#1C1939',
    lineHeight: 20,
    fontWeight: '700',
    paddingBottom: 5,
  },
  contactInfo: {
    fontSize: 12,
    color: '#9EA6BE',
    lineHeight: 15,
    fontWeight: '700',
  },
  Divider4: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#D2D1D7',
    marginRight: 30,
    marginLeft: 40,
    marginBottom: 20,
  },
  profileCardContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 20,
    width: '50%',
    marginTop: 20,
    margin: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  profileImage: {
    width: 70,
    height: 70,
    borderRadius: 25,
  },
  profileName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1C1939',
  },
  ProfileNumber: {
    color: '#9EA6BE',
    lineHeight: 15,
    fontSize: 12,
    fontWeight: '700',
  },
  HeaderTitle: {
    textAlign: 'center',
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 28,
  },
  HeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    paddingVertical: 30,
  },
  transferChannel: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 5,
  },
  searchContainer: {
    flexDirection: 'row',
    marginTop: 20,
    alignItems: 'center',
    backgroundColor: '#F9F9FB',
    borderRadius: 25,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  searchLabel: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginLeft: 15,
    color: '#9EA6BE',
  },
  subSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 18,
    color: '#1C1939',
  },
  subSectionContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  allContact: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 23,
    color: '#1C1939',
  },
});
