import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    paddingBottom: 60,
    backgroundColor: '#fff',
    marginTop: 10,
  },
  HeaderContainer: {
    width: '100%',
    height: 290,
    backgroundColor: '#7165E3',
    marginTop: 10,
  },
  HeaderProfileSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    paddingTop: 20,
  },
  profileName: {
    color: '#fff',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '400',
  },
  balanceContainer: {
    paddingHorizontal: 30,
    justifyContent: 'center',
  },
  amountTxt: {
    color: '#fff',
    fontSize: 35,
    lineHeight: 45,
    fontWeight: '700',
  },
  availbalance: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 19,
  },
  cardContainer: {
    position: 'absolute',
    bottom: '-30%',
    left: 0,
    right: 0,
    paddingHorizontal: 20,
  },
  cardWrapper: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 3,
  },
  cardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
  },
  cardTitle: {
    color: '#1C1939CC',
    fontSize: 12,
    lineHeight: 14,
    marginBottom: 5,
    fontWeight: '400',
    marginLeft: 20,
  },
  cardAmount: {
    color: '#1C1939',
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '700',
    marginLeft: 10,
  },

  cardDescriptionContainer: {
    paddingHorizontal: 30,
    paddingTop: 10,
  },
  cardDescription: {
    color: '#1C1939',
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
  },
  cardTellMore: {
    color: '#7165E3',
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
  },
  ActivityContainer: {
    marginTop: 120,
    paddingHorizontal: 30,
  },
  activityText: {
    color: '#1C1939',
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '700',
  },
  ActivityCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  ActivityCardWrapper: {
    width: 100,
    height: 110,
    backgroundColor: '#fff',
    alignItems: 'center',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 3,
  },
  ActivityCardContent: {
    backgroundColor: '#7165E3',
    borderRadius: 5,
    width: 50,
    height: 50,
    marginTop: 20,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ActivityCardTitle: {
    color: '#1C1939',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '400',
  },
  completeRegCard: {
    paddingVertical: 30,
    paddingHorizontal: 30,
  },
  completeTitle: {
    color: '#1C1939',
    fontSize: 18,
    lineHeight: 23,
    marginBottom: 20,
    fontWeight: '700',
  },
  completeRegCardContainer: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 3,
  },
  completeRegSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  completeRegPercent: {
    color: '#1C1939',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
  },
  completeRegText: {
    fontSize: 12,
    color: '#1C1939',
    lineHeight: 15,
    fontWeight: '400',
  },
  promoContainer: {
    paddingHorizontal: 30,
  },
  promoText: {
    color: '#1C1939',
    fontSize: 18,
    lineHeight: 23,
    marginBottom: 20,
    fontWeight: '700',
  },
  promoCardContainer: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 3,
    width: '100%',
    height: 290,
    overflow: 'hidden',
  },

  promoImageContainer: {
    flex: 1,
    width: '100%',
    height: '70%',
    marginTop: -30,
  },
  promoContent: {
    paddingHorizontal: 20,
    marginTop: -30,
  },
  promoTitle: {
    color: '#1C1939',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
    marginBottom: 10,
  },
  promoDescription: {
    color: '#1C1939',
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 10,
    fontWeight: '400',
  },
  inviteNow: {
    color: '#7165E3',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
  },
  progressBarContainer: {
    paddingHorizontal: 20,
    paddingTop: 15,
  },
  continueBtn: {
    marginLeft: 20,
    fontSize: 13,
    color: '#7165E3',
    lineHeight: 20,
    marginTop: 20,
    fontWeight: '700',
  },

  Divider4: {
    marginRight: 40,
    marginLeft: 60,
  },
  Divider: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#C7C7C7',
    marginTop: 20,
  },
  Divider2: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#C7C7C7',
    marginTop: 20,
    paddingHorizontal: 20,
  },
  infoContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  personalInfoDescription: {
    marginLeft: 20,
    fontSize: 13,
    color: '#1C1939',
    lineHeight: 20,
    marginTop: 10,
    fontWeight: '400',
  },
  personalInfo: {
    marginLeft: 20,
    fontSize: 13,
    color: '#1C1939',
    lineHeight: 18,
    fontWeight: '700',
  },

  Icon: {
    // width: 30,
    // height: 30,
  },
});
